# Generated by Django 5.2.15 on 2026-06-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='DJPOS', max_length=127)),
                ('store_address', models.TextField()),
                ('currency', models.CharField(default='PKR', max_length=127)),
                ('owner_name', models.CharField(default='YEAGER', max_length=127)),
                ('owner_phone_number', models.CharField(default='+92-321-748-0678', max_length=31)),
                ('store_category', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('GENERAL_STORE', 'General Store'), ('DOLLAR_STORE', 'Dollar Store'), ('APPAREL', 'Apparel'), ('GIFT_STORE', 'Gift Store')], default='GENERAL_STORE', max_length=31)),
                ('shift_duration', models.CharField(default='8-hrs', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SIGNIN', 'Signin'), ('SIGNOUT', 'Signout'), ('ACCESS', 'Access'), ('EDIT', 'Edit'), ('CREATE', 'Create')], default='SIGNIN', max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
