# Generated by Django 5.2.14 on 2026-06-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_organization_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_logs",
                to="users.organization",
            ),
        ),
    ]
