# Generated by Django 5.2.14 on 2026-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_organization_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("cashier", "Cashier"),
                ],
                max_length=31,
                null=True,
            ),
        ),
    ]
