# Generated by Django 5.2.14 on 2026-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userlog_device_id_userlog_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
