# Generated by Django 5.2.14 on 2026-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userlog_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SIGNIN", "Signin"),
                    ("SIGNOUT", "Signout"),
                    ("ACCESS", "Access"),
                    ("EDIT", "Edit"),
                    ("CREATE", "Create"),
                    ("CREATE_TERMINAL", "Create Terminal"),
                    ("DELETE_TERMINAL", "Delete Terminal"),
                ],
                default="SIGNIN",
                max_length=127,
            ),
        ),
    ]
