# Generated by Django 5.2.14 on 2026-09-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
        ("users", "0009_alter_userlog_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("terminal_name", models.CharField(default="Till", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_codes",
                        to="users.organization",
                    ),
                ),
            ],
        ),
    ]
