# Generated by Django 5.2.14 on 2026-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredientstock_remove_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='identifier',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
