# Generated by Django 5.2.14 on 2026-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_is_active_item_is_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
