# Generated by Django 5.2.14 on 2026-06-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, null=True),
        ),
    ]
