# Generated by Django 5.2.14 on 2026-05-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='bundle_included',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_by', to='inventory.bundle'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='items',
            field=models.ManyToManyField(related_name='bundles', through='inventory.BundleItem', to='inventory.bundle'),
        ),
    ]
