# Generated by Django 5.2.14 on 2026-05-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_bundleitem_bundle_included_alter_bundle_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle_included',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_by', to='inventory.bundle'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
