# Generated by Django 5.2.14 on 2026-06-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itemingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstock',
            name='added_as',
            field=models.CharField(choices=[('ITEM', 'Item'), ('STOCK', 'Stock')], default='STOCK', max_length=32, null=True),
        ),
    ]
