# Generated by Django 5.2.15 on 2026-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredientstock_added_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstock',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
