# Generated by Django 5.2.15 on 2026-06-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ingredientstock_item_id'),
        ('pos', '0004_cartitem_notes_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='pos.sale'),
        ),
    ]
