# Generated by Django 5.2.14 on 2026-06-28 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stocklog_sale"),
        ("users", "0002_organization_alter_settings_store_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundles",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="ingredientstock",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_stock",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="stocklog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_logs",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="stocklog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="identifier",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("organization", "identifier"),
                name="unique_category_identifier_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("organization", "sku"), name="unique_item_sku_per_org"
            ),
        ),
    ]
