# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


def backfill_unit_price(apps, schema_editor):
    CartItem = apps.get_model("pos", "CartItem")
    for ci in CartItem.objects.filter(item__isnull=False).select_related("item"):
        ci.unit_price = ci.item.retail_price
        ci.save(update_fields=["unit_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="bundle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="inventory.bundle",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="inventory.item",
            ),
        ),
        migrations.RunPython(backfill_unit_price, migrations.RunPython.noop),
    ]
