# Generated by Django 5.2.15 on 2026-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_cartitem_bundle_unit_price_nullable_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_cus',
            field=models.CharField(blank=True, default='WALK_IN', max_length=50),
        ),
    ]
