# Generated by Django 5.2.15 on 2026-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_customer_address_customer_type_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
