# Generated by Django 5.2.14 on 2026-09-22 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_alter_organization_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="device_id",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="sale",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
